#!/usr/bin/bash

tmux kill-server
cd ~/portfolio-site
git fetch
git reset origin/main --hard
tmux new -d -s portfolio 'cd ~/portfolio-site && source python3-virtualenv/bin/activate && pip install -r requirements.txt && flask run --host=0.0.0.0'
